#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_TURN_SPEED 0.75
#define DEFAULT_GOTO_SPEED 0.75

#define GOTO_OBSTACLE_COOLDOWN 100

#define GOTO_TOLERANCE 100
#define TURNTO_TOLERANCE 22

#define GOTO_ANGLE_TOLERANCE 22
#define GOTO_TURN_SPEED 1.5


#endif