#ifndef DEFAULTS_H
#define DEFAULTS_H

#define DEFAULT_TURN_SPEED 0.5
#define DEFAULT_GOTO_SPEED 0.5

#define GOTO_OBSTACLE_COOLDOWN 100

#define GOTO_TOLERANCE 100
#define TURNTO_TOLERANCE 10

#define GOTO_ANGLE_TOLERANCE 20
#define GOTO_TURN_SPEED 0.5


#endif